"""empty message

Revision ID: 529df7cf5c9b
Revises: e29c6a092c8f
Create Date: 2016-07-10 20:45:48.213523

"""

# revision identifiers, used by Alembic.
revision = '529df7cf5c9b'
down_revision = 'e29c6a092c8f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spotify_accesstoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.String(length=256), nullable=True),
    sa.Column('token_type', sa.String(length=16), nullable=True),
    sa.Column('scope', sa.String(length=64), nullable=True),
    sa.Column('expires_in', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(length=256), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spotify_accesstoken')
    ### end Alembic commands ###
