"""empty message

Revision ID: f54b0ecaf71d
Revises: 2b873d922e82
Create Date: 2016-06-07 22:47:33.500750

"""

# revision identifiers, used by Alembic.
revision = 'f54b0ecaf71d'
down_revision = '2b873d922e82'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_accesstokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token_type', sa.String(length=16), nullable=True),
    sa.Column('scope', sa.String(length=64), nullable=True),
    sa.Column('access_token', sa.String(length=40), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token')
    )
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_table('github_accesstokens')
    ### end Alembic commands ###
